name: fire_line_diff
description: A dart line diff tool.
version: 1.5.0
repository: https://github.com/SedlarDavid/fire_line_diff
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dev_dependencies:
  test: ^1.16.8